<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>RUDA NEWS INFO</title>
</head>
<body>
<hr>

<div style="margin-top: 50px;margin-left: 200px">
<h1>News info</h1>
<h1><b>Компания : </b>${newss.company}<br></h1>
    <h1><b>Описание : </b>${newss.description}<br></h1>
        <h1><b>Индустрия : </b>${newss.industry}<br></h1>
            <h1><b>Время работы : </b>${newss.time}<br></h1>
                <h1><b>Зарплата : </b>${newss.salary}<br></h1>
                    <h1><b>Автор: </b>${newss.user.email}</h1>
</div>

<hr>
</body>
</html>